import json
from pathlib import Path
# Product entries share their vendor's official mark where no distinct mark exists.
groups = {
'Languages': '''TypeScript|typescript|web frontend javascript;JavaScript|javascript|web node frontend;Python|python|ai data backend agent;Swift|swift|ios macos apple native;Kotlin|kotlin|android mobile;C#|csharp|microsoft enterprise dotnet;Go|go|backend cloud microservice;Rust|rust|systems performance desktop;Java|openjdk|enterprise jvm backend;Dart|dart|flutter mobile;C++|cplusplus|native performance gaming;C|c|embedded systems;Ruby|ruby|rails web;PHP|php|web wordpress;Elixir|elixir|realtime concurrent;Scala|scala|spark data;R|r|statistics data;Julia|julia|scientific computing;Kotlin Multiplatform|kotlin|cross-platform mobile ios android;Zig|zig|systems native''',
'Frontend / Mobile': '''React|react|web frontend saas;Next.js|nextdotjs|web saas b2b next.js;Vue|vuedotjs|web frontend;Nuxt|nuxtdotjs|vue web;Angular|angular|enterprise web;Svelte|svelte|web frontend;Astro|astro|website content;Tailwind CSS|tailwindcss|web frontend css saas;HTML5|html5|web website;CSS3|css3|web styling;SwiftUI|swift|ios macos native apple;AppKit|apple|macos native desktop;Mac Catalyst|apple|ios macos catalyst;iOS|apple|ios iphone native;macOS|apple|macos desktop native;React Native|react|cross-platform mobile ios android;Flutter|flutter|cross-platform mobile desktop;Electron|electron|desktop cross-platform javascript;Tauri|tauri|desktop cross-platform rust;Android|android|android mobile;Expo|expo|react native mobile;Vite|vite|web build;Remix|remix|web react;Gatsby|gatsby|web static;SolidJS|solid|web frontend;Qwik|qwik|web frontend;Alpine.js|alpinedotjs|web frontend;Lit|lit|web components;Bootstrap|bootstrap|web css;Webflow|webflow|website design''',
'Backend & APIs': '''FastAPI|fastapi|python api ai backend;Node.js|nodedotjs|javascript backend realtime;Express|express|node backend api;NestJS|nestjs|typescript enterprise backend;.NET 9|dotnet|microsoft enterprise c# backend;ASP.NET Core|dotnet|microsoft api enterprise;Django|django|python web backend;Flask|flask|python api backend;Spring Boot|springboot|java enterprise backend;Rails|rubyonrails|ruby saas backend;Laravel|laravel|php backend;Phoenix|phoenixframework|elixir realtime;GraphQL|graphql|api query;gRPC|google|rpc microservice;Hono|hono|edge api;Fastify|fastify|node api;Deno|deno|typescript runtime;Bun|bun|javascript runtime;Socket.IO|socketdotio|realtime websocket;Temporal|temporal|workflow durable orchestration''',
'Agent Frameworks': '''Microsoft AutoGen|microsoft|agent multi-agent orchestration microsoft autonomous;Semantic Kernel|microsoft|agent microsoft enterprise orchestration;LangChain|langchain|ai agent rag orchestration;LangGraph|langchain|multi-agent graph workflow;CrewAI|crewai|multi-agent autonomous crew;LlamaIndex|llamaindex|rag agent retrieval;Azure AI Foundry|microsoftazure|azure microsoft ai agent;OpenAI API|openai|ai agent llm gpt;Anthropic Claude|anthropic|ai agent llm claude;Microsoft Copilot Studio|microsoft|microsoft enterprise agent copilot;Hugging Face|huggingface|ai models machine learning;Ollama|ollama|local ai llm;PyTorch|pytorch|machine learning ai;TensorFlow|tensorflow|machine learning ai;scikit-learn|scikitlearn|machine learning data;Jupyter|jupyter|data python notebook;Apache Spark|apachespark|data streaming analytics;Apache Kafka|apachekafka|realtime streaming media pipeline;Apache Flink|apacheflink|realtime streaming pipeline;FFmpeg|ffmpeg|media video streaming pipeline''',
'Database & Cache': '''PostgreSQL|postgresql|database sql saas postgres;Redis|redis|cache realtime streaming;Supabase|supabase|database auth postgres saas;MongoDB|mongodb|database document;MySQL|mysql|database sql;SQLite|sqlite|local mobile database;Azure Cosmos DB|microsoftazure|microsoft azure database;Pinecone|pinecone|ai rag vector database;Weaviate|weaviate|ai vector rag;Qdrant|qdrant|ai vector rag;Chroma|chroma|ai vector rag;Elasticsearch|elasticsearch|search analytics;ClickHouse|clickhouse|analytics streaming data;DuckDB|duckdb|analytics data;Firebase|firebase|mobile realtime database;Prisma|prisma|typescript database orm;Drizzle|drizzle|typescript sql orm;DynamoDB|amazondynamodb|aws serverless database;MariaDB|mariadb|database sql;Neo4j|neo4j|graph database;PlanetScale|planetscale|database mysql;CockroachDB|cockroachlabs|distributed sql''',
'Cloud & Hosting': '''Microsoft Azure|microsoftazure|azure microsoft enterprise cloud;Azure Functions|microsoftazure|azure microsoft serverless;Azure Container Apps|microsoftazure|azure microsoft containers microservices;AWS|amazonaws|cloud aws hosting;Google Cloud|googlecloud|cloud google hosting;Cloudflare|cloudflare|edge web hosting;Vercel|vercel|next.js web saas hosting;Netlify|netlify|web hosting;Docker|docker|container backend devops;Kubernetes|kubernetes|enterprise cloud container orchestration;Terraform|terraform|cloud infrastructure devops;GitHub Actions|githubactions|ci cd devops;GitLab|gitlab|ci devops;DigitalOcean|digitalocean|cloud hosting;Render|render|backend web hosting;Railway|railway|backend web hosting;Fly.io|flydotio|edge backend hosting;AWS Lambda|awslambda|aws serverless;Amazon S3|amazons3|aws media storage;NGINX|nginx|web proxy streaming;Grafana|grafana|observability monitoring;Prometheus|prometheus|monitoring metrics;Sentry|sentry|monitoring errors;Datadog|datadog|enterprise monitoring;OpenTelemetry|opentelemetry|observability tracing;Ansible|ansible|devops infrastructure;Pulumi|pulumi|cloud infrastructure;Argo CD|argo|kubernetes gitops'''
}
entries=[]
for category, raw in groups.items():
 for row in raw.split(';'):
  name,slug,words=row.split('|')
  special={'Microsoft AutoGen':'autogen','Microsoft Azure':'azure','Microsoft Copilot Studio':'copilot-studio','.NET 9':'dotnet','Next.js':'nextjs','Node.js':'nodejs','C#':'csharp','C++':'cpp'}
  id=special.get(name,name.lower().replace(' ','-').replace('.','').replace('/',''))
  entries.append(dict(id=id,name=name,category=category,slug=slug,hex='#'+{'microsoft':'0078D4','microsoftazure':'0078D4','apple':'111111'}.get(slug,'555555'),keywords=[name.lower(),*words.split()]))
Path('shared/catalog.json').write_text(json.dumps(entries,indent=2)+'\n')
print(len(entries),'technologies')
